version: 2
jobs:
  build-quantal-telephones-service:

    working_directory: ~/quantal-telephones-service

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

    steps:

      - checkout

      - restore_cache:
          key: quantal-telephones-service-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - run: mkdir -p /var/log
      - run: sudo touch /var/log/springboot_log.log /var/log/app_log.log /var/log/app_log.json && sudo chmod 777 /var/log/springboot_log.log /var/log/app_log.log /var/log/app_log.json

      - save_cache:
          paths:
            - ~/.m2
          key: quantal-telephones-service-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/quantal-telephones-service-0.0.1-SNAPSHOT.jar
workflows:
  version: 2
  build_project:
    jobs:
      - build-quantal-telephones-service