version: '3'
networks:
  default:
    external:
      name: compose_container_services_networks
services:
  quantal-telephones-service:
    build:
      context: ./../../
      dockerfile: ./docker/Dockerfile
    ports:
      - ${WEB_APP_PORT:-7001}:8080
    environment:
      - DB_HOST=postgres-quantal-telephones-service
      - DB_PORT=5432
      - LOGZIO_TOKEN=${LOGZIO_TOKEN}
    command: ["/wait-for-it.sh", "-t", "30", "postgres-quantal-telephones-service:5432", "--", "java",  "-jar", "~/telephones-0.0.1-SNAPSHOT.jar"]
    volumes:
      - /private/var/docker/log/telephones:/var/log

  # The postgres database
  postgres-quantal-telephones-service:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      #- "5439:5432"
      - ${DB_PORT_EXPOSED_ON_HOST:-5439}:5432
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=quantal_telephones_db
      - PG_PASSWORD=postgres
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=