version: '3'
services:
  quantalmicroservicetemplate:
    build:
      context: ./../../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres_quantalmicroservicetemplate
      - DB_PORT=5432
    command: ["/wait-for-it.sh", "postgres_quantalmicroservicetemplate:5432", "--", "java",  "-jar", "~/quantalmicroservicetemplate-0.0.1-SNAPSHOT.jar"]

  # The postgres database
  postgres_quantalmicroservicetemplate:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5434:5432"
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - PG_PASSWORD=postgres
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=